baseurl = "http://127.0.0.1:1313"
title = "Gaffer On Games"
canonifyurls = true
paginate = 1000
languageCode = "en-us"
copyright = "Copyright © Glenn Fiedler, 2004 - 2019"
buildDrafts = true

[author]
  name = "Glenn Fiedler"

[params]
  DateForm = "Monday, January 2, 2006"
  Description = "Glenn Fiedler's Game Development Articles"
  Author = "Glenn Fiedler"
  email = "glenn.fiedler@gmail.com"
  Ganalytics = "UA-17769864-1"

[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/glennfiedler/"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/gafferongames"

[[params.social]]
  title = "github"
  url = "https://github.com/gafferongames"
