baseurl = "https://gafferongames.com"
title = "Gaffer On Games"
canonifyurls = true
paginate = 1000
languageCode = "en-us"
copyright = "© The Network Protocol Company, Inc."

[author]
  name = "Glenn Fiedler"

[params]
  DateForm = "Monday, January 2, 2006"
  Description = "Glenn Fiedler's Game Development Articles"
  Author = "Glenn Fiedler"
  email = "glenn.fiedler@gmail.com"
  Ganalytics = "UA-17769864-1"

[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/glennfiedler/"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/gafferongames"

[[params.social]]
  title = "github"
  url = "https://github.com/gafferongames"

[[menu.main]]
  name = "Support gafferongames.com"
  url = "https://www.patreon.com/gafferongames"
