baseurl = "http://new.gafferongames.com"
title = "Gaffer On Games"
canonifyurls = true
paginate = 10
languageCode = "en-us"
copyright = "© The Network Protocol Company, Inc."

[author]
    name = "Glenn Fiedler"

[params]
  DateForm = "Monday, January 2, 2006"
  Description = "Glenn Fiedler's Game Development Articles"
  Author = "Glenn Fiedler"
  email = "glenn.fiedler@gmail.com"
  Ganalytics = "UA-17769864-1"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/gafferongames"

[[params.social]]
    title = "github"
    url = "https://github.com/gafferongames"

[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/gafferongames"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

[[menu.main]]
  name = "Support gafferongames.com"
  url = "http://www.patreon.com/gafferongames"
