version: "3"

services:

  nginx:
    build: nginx
    depends_on: 
      - "webserver"
      - "wordpress"
    links:
      - "webserver:web"
      - "wordpress:wp"
    ports:
      - "80:80"
      - "443:443"

  webserver:
    build: webserver
    depends_on: 
      - "redis"
    links:
      - "redis:db"

  redis:
    build: redis

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8000:80"

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  mysql_data:
