version: "3"
services:

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "webserver:web" 

  webserver:
    build: webserver
    links:
      - "redis:db"

  redis:
    build: redis
