version: "3"
services:

  nginx:
    build: nginx
    links:
      - "webserver:web"
    ports:
      - "80:80"
      - "443:443"

  webserver:
    build: webserver
    links:
      - "redis:db"

  redis:
    build: redis
