version: "3"

services:

  nginx:
    build: nginx
    depends_on: 
      - "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/gafferongames:ro

  webserver:
    build: webserver
    depends_on: 
      - "redis"
    volumes:
      - ./videos:/go/bin/videos:ro

  redis:
    build: redis
