version: "3"

services:

  nginx:
    build: nginx
    depends_on: 
      - "webserver"
      - "wordpress"
    ports:
      - "80:80"
      - "443:443"

  webserver:
    build: webserver
    depends_on: 
      - "redis"

  redis:
    build: redis
