version: "3"
services:

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"

  webserver:
    build: webserver
    ports:
      - "8080:8080"
    links:
      - "redis:db"

  redis:
    build: redis
